@startuml

class 예매
class 상영
class 영화
class 할인정책
class 할인조건

예매 "*" - "1" 상영
상영 "*" - "1" 영화
영화 "1" - "0..1" 할인정책
할인정책 "1" - "1..*" 할인조건

할인정책 <|-- 금액할인정책
할인정책 <|-- 비율할인정책

할인조건 <|-- 순번조건
할인조건 <|-- 기간조건

@enduml